# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  message-mastrix:
    runs-on: ubuntu-latest
    steps:
      - name: matrix-message
      # You may pin to the exact commit or the version.
      # uses: s3krit/Matrix-Message@70ad3fb812ee0e45ff8999d6af11cafad11a6ecf
        uses: s3krit/Matrix-Message@v0.0.3
        with:
          # Matrix room ID, specified in channels advanced settings
          room_id: ${{ secrets.MATRIX_ROOM_ID }} 
          # Access token required to send to matrix server
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          # Message to send in plaintext format
          message: "Code was pushed or a PR made on https://github.com/magicstone-dev/ecko"
