name: Set timestamp

on:
  pull_request_target: 
    types: [closed]
    branches: [main]
  workflow_dispatch:
  
jobs:
  Stamp:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Get build date
        run: echo date=`date +%F` > $GITHUB_ENV

      - name: Update timestamp
        run: |
              echo 'Today's date is' "${{ env.date }}"
              echo "${{ env.date }}" > .build
      - name: Commit timestamp to main branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
